# Usa una imagen de Node.js como base
FROM node:14

# Establece el directorio de trabajo
WORKDIR /todoList_Softek

# Copia los archivos del proyecto al contenedor
COPY . .

# Instala las dependencias
RUN npm install

# Inicia la aplicación
CMD ["npm", "run", "dev"]
